### ISSUE TITLE
Make PyDDQ work with Zeppelin

### ISSUE THREAD

**Issue by FRosner** [FRosner/drunken-data-quality#105]
``` python
%pyspark
import sys
print type(sys.stdout)

<class '__main__.Logger'>
```

``` python
%pyspark
from pyddq.core import Check

Traceback (most recent call last):
  File "/tmp/zeppelin_pyspark-3897329280835991811.py", line 239, in <module>
    eval(compiledCode)
  File "<string>", line 1, in <module>
  File "/misc/anaconda2/lib/python2.7/site-packages/pyddq/core.py", line 1, in <module>
    from reporters import ConsoleReporter
  File "/misc/anaconda2/lib/python2.7/site-packages/pyddq/reporters.py", line 5, in <module>
    class Reporter(object):
  File "/misc/anaconda2/lib/python2.7/site-packages/pyddq/reporters.py", line 9, in Reporter
    def __init__(self, output_stream=FileOutputStream(sys.stdout)):
  File "/misc/anaconda2/lib/python2.7/site-packages/pyddq/streams.py", line 39, in __init__
    mode = descriptor.mode
AttributeError: 'Logger' object has no attribute 'mode'

```

**Comment by FRosner** [comment]
@Gerrrr pliez fiks
