### ISSUE TITLE
Build broken

### ISSUE THREAD

**Issue by FRosner** [FRosner/drunken-data-quality#140]
https://travis-ci.org/FRosner/drunken-data-quality/jobs/310284764#L2886

```
0.52s$ sudo python setup.py test
/home/travis/build/FRosner/drunken-data-quality/python/.eggs/PyScaffold-2.5.8-py2.7.egg/pyscaffold/contrib/setuptools_scm/setuptools_scm/git.py:56: UserWarning: "/home/travis/build/FRosner/drunken-data-quality" is shallow and may cause errors
  warnings.warn('"%s" is shallow and may cause errors' % (wd.path,))
running test
Traceback (most recent call last):
  File "setup.py", line 63, in <module>
    setup_package()
  File "setup.py", line 58, in setup_package
    "integration_test": IntegrationTestCommand
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/home/travis/build/FRosner/drunken-data-quality/python/.eggs/PyScaffold-2.5.8-py2.7.egg/pyscaffold/pytest_runner.py", line 89, in run
    self.distribution.fetch_build_eggs(self.distribution.tests_require)
  File "/usr/local/lib/python2.7/dist-packages/setuptools/dist.py", line 446, in fetch_build_eggs
    replace_conflicting=True,
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 866, in resolve
    new_requirements = dist.requires(req.extras)[::-1]
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2590, in requires
    "%s has no such extra feature %r" % (self, ext)
pkg_resources.UnknownExtra: urllib3 1.7.1 has no such extra feature 'secure'
```

**Comment by FRosner** [comment]
Any ideas @Gerrrr?

**Comment by Gerrrr** [comment]
Hey @FRosner 

Sorry for the late response!
I am a bit busy until the end of the week. I am going to take a look at the broken build in the middle of the next week or so.

**Comment by FRosner** [comment]
Other people have the same error: https://github.com/micropython/micropython/issues/3246
